import type { Metadata } from "next";
import AppSidebar from "@/components/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { createClient } from "@/utils/supabase/server";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const supabase = await createClient()
    const {data} = await supabase.from('chat').select()

    return (
        <>
            <SidebarProvider>
                <div className="flex min-h-screen">
                    <AppSidebar chats={data ?? []} />
                    <main className="flex-1 md:ml-64">
                        <div className="container mx-auto py-4">{children}</div>
                    </main>
                </div>
            </SidebarProvider>
        </>
    );
}
