import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div className="flex min-h-screen bg-white dark:bg-gray-900 text-black dark:text-white">
            <aside className="w-64 bg-gray-100 dark:bg-gray-800 p-4 hidden md:block">
                <h2 className="text-lg font-bold mb-4">Sidebar</h2>
                <nav>
                    <ul className="space-y-2">
                        <li><a href="#" className="block p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700">What is supabase</a></li>
                        <li><a href="#" className="block p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700">What is typescript</a></li>
                        <li><a href="#" className="block p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700">What is react</a></li>
                    </ul>
                </nav>
            </aside>

            <div className="flex-1 flex flex-col">

                <header className="p-4 shadow-md flex justify-between items-center bg-white dark:bg-gray-900">
                    <button className="md:hidden p-2 rounded bg-gray-200 dark:bg-gray-700">☰</button>
                    <h1 className="text-xl font-bold">Optimus AI</h1>
                </header>

                <main className="flex-1 p-4 overflow-y-auto">{children}</main>
            </div>
        </div>

    );
}
